# path to models (relative to demo.py)
models_path:         'models/'

label_types:
    - "B-RES"
    - "I-RES"
    - "B-DIS"
    - "I-DIS"
    - "B-OCC"
    - "I-OCC"

# pred_type: [dark_highlight, light_highlight]
demo_colors:
  res: ["#17becf", "#9edae5"] # blues
  dis: ["#9467bd", "#c5b0d5"] # purples
  occ: ["#74c476", "#c7e9c0"] # greens

default_text: "This place was really great!  I know all Teppanyaki places are very similar, and the \"show\" was typical.  But the food here really was fantastic!  Great fresh veggies and meat!  They also had a sautéed spinach that was part of the meal.  Never seen that before, but it was delicious!  Very reasonable, and large portions.  Their Sake Bombers were also pretty cheap.  Will return for sure!"
